version: "2.2"
services:
  db:
    image: mysql/mysql-server:8.0.26
    volumes:
      - mysql-data:/data/db
      - ./mysql-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: nodedb
  node:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local
